#! /bin/sh
#  /etc/init.d/autoscaling

### BEGIN INIT INFO
# Provides:          autoscaling
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the AutoScaling service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   Christof Hlipala <christof.hlipala[AT]gmail.com>
# Date:     05/04/2014

NAME="autoscaling"
DESC="AutoScaling service"

# The path to Jsvc
EXEC="/usr/bin/jsvc"

# The path to the folder containing autoscaling.jar
FILE_PATH="/usr/share/$NAME"

# The path to the folder containing the java runtime
#JAVA_HOME="/usr/bin/java"
JAVA_HOME="$( readlink -f "$( which java )" | sed "s:bin/.*$::" )"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/autoscaling.jar:$FILE_PATH/lib/commons-daemon-1.0.15.jar:$FILE_PATH/lib/commons-httpclient-3.1.jar:$FILE_PATH/lib/commons-logging-1.1.3.jar:$FILE_PATH/lib/commons-codec-1.9.jar:$FILE_PATH/lib/simple-5.1.5.jar:$FILE_PATH/lib/log4j.jar"

# The fully qualified name of the class to execute
CLASS="hlipala.autoscaling.Main"

# Any command line arguments to be passed to the our Java Daemon implementations init() method 
ARGS=""

#The user to run the daemon as
USER="root"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="/var/log/$NAME.out"

# System.err writes to this file...
LOG_ERR="/var/log/$NAME.err"

jsvc_exec()
{   
    cd $FILE_PATH
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)  
        echo "Starting the $DESC..."        
        
        # Start the service
        jsvc_exec
        
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."
        
        # Stop the service
        jsvc_exec "-stop"       
        
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "Restarting the $DESC..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac